name: Deploy Service

on:
  push:
    branches: ['deploy']

jobs:  
  deploy:
    name: Deploy image to vps
    runs-on: self-hosted
    steps:
    - name: Setup github runner with ssh # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.VPS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VPS_HOST }} > ~/.ssh/known_hosts
    - name: login to remote server
      run: ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
        sudo docker kill app1 &&
        sudo docker rm app1 &&
        sudo docker rmi ghcr.io/daedalus1948/automation_test:release &&
        sudo docker pull ghcr.io/daedalus1948/automation_test:release && 
        sudo docker run -d -p 8080:8080 --name app1 ghcr.io/daedalus1948/automation_test:release"
    - name: remove ssh directory after 
      run: rm -rf ~/.ssh