name: Start Service

on: 
  workflow_dispatch: # manually trigger workflow via github actions web interface

env:
  APP_NAME: app1

jobs:
  start_service:
    name: Start Service
    runs-on: self-hosted
    steps:
      - name: Start Service
        run: ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "sudo docker start $APP_NAME"

