name: Stop Service

on: 
  workflow_dispatch: # manually trigger workflow via github actions web interface

env:
  APP_NAME: app1

jobs:
  stop_service:
    name: Stop Service
    runs-on: self-hosted
    steps:
      - name: Setup github runner with ssh # https://stackoverflow.com/a/70447517
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} > ~/.ssh/known_hosts
      - name: Stop Service
        run: ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "sudo docker stop $APP_NAME"
      - name: remove ssh directory after 
        run: rm -rf ~/.ssh